version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/copy.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/restart.sh
      timeout: 300
      runas: ubuntu
